// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cluster: typeof import('./components/composition/Cluster.vue')['default']
    ColorEditor: typeof import('./components/TokenDashboard/ColorEditor.vue')['default']
    Counter: typeof import('./components/blocks/Counter.vue')['default']
    FontEditor: typeof import('./components/TokenDashboard/FontEditor.vue')['default']
    Footer: typeof import('./components/blocks/Footer.vue')['default']
    Hero: typeof import('./components/composition/Hero.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpaceEditor: typeof import('./components/TokenDashboard/SpaceEditor.vue')['default']
    TokenEditor: typeof import('./components/TokenDashboard/TokenEditor.vue')['default']
    ViewportEditor: typeof import('./components/TokenDashboard/ViewportEditor.vue')['default']
  }
}

export {}
