// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/blocks/Counter.vue')['default']
    Flow: typeof import('./components/composition/Flow.vue')['default']
    Footer: typeof import('./components/blocks/Footer.vue')['default']
    Hero: typeof import('./components/composition/Hero.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
